### ISSUE TITLE
NuGet package availability?

### ISSUE THREAD

**Issue by SuperJMN** [yusufuzun/dbscan#20]
Is there any NuGet package for this project? 

Thanks!

**Comment by viceroypenguin** [comment]
@SuperJMN fyi https://github.com/viceroypenguin/DBSCAN does have a nuget package available

**Comment by SuperJMN** [comment]
> @SuperJMN fyi https://github.com/viceroypenguin/DBSCAN does have a nuget package available

OK, thanks! but that's another project with another the API, isn't it?

**Comment by viceroypenguin** [comment]
@SuperJMN Yes, it is a separate project with a different API.

**Comment by SuperJMN** [comment]
Thanks for the info. It would be interesting if this was pushing nuget packages. I might fork it to add some nuget building and pushing logic.
